export const CREATE_QUERY = 'CREATE_QUERY';
export const ADD_PAST_QUERIES = 'ADD_PAST_QUERIES';
export const INITIALIZE_QUERY_SEARCH = 'INITIALIZE_QUERY_SEARCH';
export const FETCH_QUERIES = 'FETCH_QUERIES';
